version: "3.9"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - 3000:3000  
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    expose:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 1883:1883 # Add this line to expose the MQTT port
      - 9000:9001
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mqtt.nginx.conf:/etc/nginx/mqtt.nginx.conf:ro # Add this line to include the MQTT configuration
    depends_on:
      - application