version: "3.9"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - 3000:3000  
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application